import type { AtlasEntity, AtlasLink, AtlasScene } from "@/lib/atlas/types";

/**
 * Current European Monarchies — 2025 snapshot.
 * 12 reigning monarchs, their houses, capitals, and key descent links.
 */

// ─── Places ───────────────────────────────────────────────────────────────────
export const monarchyPlaces: AtlasEntity[] = [
  {
    id: "london",
    kind: "place",
    name: "London",
    summary: "Capital of the United Kingdom; seat of the House of Windsor.",
    description: "Buckingham Palace is the official London residence and administrative HQ of the British monarch.",
    coords: { lat: 51.5014, lng: -0.1419 },
    tags: ["capital", "uk", "palace"],
  },
  {
    id: "madrid",
    kind: "place",
    name: "Madrid",
    summary: "Capital of Spain; seat of the House of Bourbon-Anjou.",
    description: "The Royal Palace of Madrid (Palacio Real) is the official residence of the Spanish royal family.",
    coords: { lat: 40.4168, lng: -3.7038 },
    tags: ["capital", "spain", "palace"],
  },
  {
    id: "amsterdam",
    kind: "place",
    name: "Amsterdam / The Hague",
    summary: "Dutch royal seat; House of Orange-Nassau.",
    description: "Royal Palace of Amsterdam for ceremonies; Huis ten Bosch in The Hague is the working royal residence.",
    coords: { lat: 52.3676, lng: 4.9041 },
    tags: ["capital", "netherlands", "palace"],
  },
  {
    id: "brussels",
    kind: "place",
    name: "Brussels",
    summary: "Capital of Belgium; seat of the House of Belgium.",
    description: "Royal Palace of Brussels is the official palace; Château de Laeken is the private residence.",
    coords: { lat: 50.8503, lng: 4.3517 },
    tags: ["capital", "belgium", "palace"],
  },
  {
    id: "copenhagen",
    kind: "place",
    name: "Copenhagen",
    summary: "Capital of Denmark; seat of the House of Glücksburg (Danish branch).",
    description: "Christiansborg Palace is the official working residence; Marselisborg for summer.",
    coords: { lat: 55.6761, lng: 12.5683 },
    tags: ["capital", "denmark", "palace"],
  },
  {
    id: "oslo",
    kind: "place",
    name: "Oslo",
    summary: "Capital of Norway; seat of the House of Glücksburg (Norwegian branch).",
    description: "Royal Palace of Oslo sits at the end of Karl Johans gate.",
    coords: { lat: 59.9139, lng: 10.7522 },
    tags: ["capital", "norway", "palace"],
  },
  {
    id: "stockholm",
    kind: "place",
    name: "Stockholm",
    summary: "Capital of Sweden; seat of the House of Bernadotte.",
    description: "Royal Palace (Kungliga slottet) in Gamla Stan is the official Swedish royal residence.",
    coords: { lat: 59.3293, lng: 18.0686 },
    tags: ["capital", "sweden", "palace"],
  },
  {
    id: "luxembourg-city",
    kind: "place",
    name: "Luxembourg City",
    summary: "Capital of Luxembourg; seat of the House of Nassau-Weilburg.",
    description: "Grand Ducal Palace sits in the historic city centre.",
    coords: { lat: 49.6116, lng: 6.1319 },
    tags: ["capital", "luxembourg", "palace"],
  },
  {
    id: "vaduz",
    kind: "place",
    name: "Vaduz",
    summary: "Capital of Liechtenstein; seat of the House of Liechtenstein.",
    description: "Vaduz Castle overlooks the capital from the hillside — still occupied by the ruling family.",
    coords: { lat: 47.1410, lng: 9.5209 },
    tags: ["capital", "liechtenstein", "castle"],
  },
  {
    id: "monaco-city",
    kind: "place",
    name: "Monaco",
    summary: "City-state; seat of the House of Grimaldi.",
    description: "Prince's Palace of Monaco sits on the Rock of Monaco.",
    coords: { lat: 43.7297, lng: 7.4142 },
    tags: ["principality", "monaco", "palace"],
  },
  {
    id: "andorra-la-vella",
    kind: "place",
    name: "Andorra la Vella",
    summary: "Capital of Andorra; co-principality (France + Spain).",
    description: "Unique in Europe: Andorra has two co-princes — the French President and the Bishop of Urgell.",
    coords: { lat: 42.5063, lng: 1.5218 },
    tags: ["capital", "andorra", "co-principality"],
  },
  {
    id: "valletta",
    kind: "place",
    name: "Valletta",
    summary: "Capital of Malta (Commonwealth realm); King Charles III is head of state.",
    description: "Malta shares the British monarch as formal head of state.",
    coords: { lat: 35.8989, lng: 14.5146 },
    tags: ["capital", "malta", "commonwealth"],
  },
];

// ─── Houses (dynasties) ───────────────────────────────────────────────────────
export const monarchyHouses: AtlasEntity[] = [
  {
    id: "house-windsor",
    kind: "dynasty",
    name: "House of Windsor",
    summary: "British royal house since 1917; descended from the House of Saxe-Coburg and Gotha.",
    description: "Renamed Windsor from Saxe-Coburg and Gotha during WWI. Current head: King Charles III.",
    startYear: 1917,
    tags: ["dynasty", "britain", "windsor"],
  },
  {
    id: "house-bourbon-spain",
    kind: "dynasty",
    name: "House of Bourbon (Spain)",
    summary: "Spanish branch of the Bourbon dynasty, restored in 1975.",
    description: "Restored following the end of the Franco dictatorship. Current head: King Felipe VI.",
    startYear: 1700,
    tags: ["dynasty", "spain", "bourbon"],
  },
  {
    id: "house-orange-nassau",
    kind: "dynasty",
    name: "House of Orange-Nassau",
    summary: "Dutch royal house ruling since 1815.",
    description: "The orange color of the Netherlands national team traces to this house. Current head: King Willem-Alexander.",
    startYear: 1815,
    tags: ["dynasty", "netherlands", "orange"],
  },
  {
    id: "house-belgium",
    kind: "dynasty",
    name: "House of Belgium (Saxe-Coburg-Gotha)",
    summary: "Belgian royal house since 1831.",
    description: "A branch of Saxe-Coburg and Gotha. Current head: King Philippe.",
    startYear: 1831,
    tags: ["dynasty", "belgium"],
  },
  {
    id: "house-glucksburg",
    kind: "dynasty",
    name: "House of Glücksburg",
    summary: "Ruling house of Denmark, Norway, and (until recently) Greece.",
    description: "A branch of the House of Oldenburg. Current monarchs: Queen Mary (Denmark), King Harald V (Norway).",
    startYear: 1863,
    tags: ["dynasty", "denmark", "norway", "glucksburg"],
  },
  {
    id: "house-bernadotte",
    kind: "dynasty",
    name: "House of Bernadotte",
    summary: "Swedish royal house since 1818; founded by Napoleon's marshal Jean-Baptiste Bernadotte.",
    description: "Unique origin: elected by the Swedish parliament after the Napoleonic Wars. Current head: King Carl XVI Gustaf.",
    startYear: 1818,
    tags: ["dynasty", "sweden", "bernadotte"],
  },
  {
    id: "house-nassau-weilburg",
    kind: "dynasty",
    name: "House of Nassau-Weilburg",
    summary: "Luxembourg grand-ducal house since 1890.",
    description: "Current head: Grand Duke Henri.",
    startYear: 1890,
    tags: ["dynasty", "luxembourg", "nassau"],
  },
  {
    id: "house-liechtenstein",
    kind: "dynasty",
    name: "House of Liechtenstein",
    summary: "Ruling house of the Principality of Liechtenstein since 1699.",
    description: "One of only two ruling princes in Europe. Current head: Prince Hans-Adam II.",
    startYear: 1699,
    tags: ["dynasty", "liechtenstein"],
  },
  {
    id: "house-grimaldi",
    kind: "dynasty",
    name: "House of Grimaldi",
    summary: "Ruling house of Monaco since 1297 — the oldest ruling dynasty in Europe.",
    description: "Current head: Prince Albert II.",
    startYear: 1297,
    tags: ["dynasty", "monaco", "grimaldi"],
  },
];

// ─── Monarchs ─────────────────────────────────────────────────────────────────
export const monarchyPersons: AtlasEntity[] = [
  {
    id: "king-charles-iii",
    kind: "person",
    name: "King Charles III",
    calloutLabel: "Charles III",
    summary: "King of the United Kingdom since 8 September 2022.",
    description: "Born 14 November 1948. Longest-serving heir apparent in British history before acceding to the throne following the death of Queen Elizabeth II. Member of the House of Windsor.",
    startYear: 1948,
    coords: { lat: 51.5014, lng: -0.1419 },
    tags: ["monarch", "uk", "windsor"],
    portraitUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/King_Charles_III_official_portrait_%282023%29.jpg/330px-King_Charles_III_official_portrait_%282023%29.jpg",
  },
  {
    id: "queen-mary-denmark",
    kind: "person",
    name: "Queen Mary of Denmark",
    calloutLabel: "Queen Mary",
    summary: "Queen of Denmark since 14 January 2024; born in Australia.",
    description: "Born Mary Elizabeth Donaldson on 5 February 1972 in Hobart, Tasmania. Married Crown Prince Frederik in 2004. Became Queen when Frederik acceded as Frederik X on 14 January 2024.",
    startYear: 1972,
    coords: { lat: 55.6761, lng: 12.5683 },
    tags: ["monarch", "denmark", "glucksburg"],
    portraitUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Queen_Mary_of_Denmark_2024_%28cropped%29.jpg/330px-Queen_Mary_of_Denmark_2024_%28cropped%29.jpg",
  },
  {
    id: "king-frederik-x",
    kind: "person",
    name: "King Frederik X of Denmark",
    calloutLabel: "Frederik X",
    summary: "King of Denmark since 14 January 2024.",
    description: "Born 26 May 1968. Son of Queen Margrethe II who abdicated in January 2024 — the first Danish abdication in nearly 900 years.",
    startYear: 1968,
    coords: { lat: 55.6761, lng: 12.5683 },
    tags: ["monarch", "denmark", "glucksburg"],
  },
  {
    id: "king-harold-v-norway",
    kind: "person",
    name: "King Harald V of Norway",
    calloutLabel: "Harald V",
    summary: "King of Norway since 17 January 1991.",
    description: "Born 21 February 1937. First Norwegian-born king since 1387. Married Queen Sonja in 1968.",
    startYear: 1937,
    coords: { lat: 59.9139, lng: 10.7522 },
    tags: ["monarch", "norway", "glucksburg"],
  },
  {
    id: "king-carl-xvi-gustaf",
    kind: "person",
    name: "King Carl XVI Gustaf of Sweden",
    calloutLabel: "Carl XVI Gustaf",
    summary: "King of Sweden since 15 September 1973; world's longest-reigning current monarch.",
    description: "Born 30 April 1946. Married Silvia Sommerlath in 1976. Has reigned longer than any other current monarch.",
    startYear: 1946,
    coords: { lat: 59.3293, lng: 18.0686 },
    tags: ["monarch", "sweden", "bernadotte"],
    portraitUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Carl_XVI_Gustaf_2022.jpg/330px-Carl_XVI_Gustaf_2022.jpg",
  },
  {
    id: "king-willem-alexander",
    kind: "person",
    name: "King Willem-Alexander of the Netherlands",
    calloutLabel: "Willem-Alexander",
    summary: "King of the Netherlands since 30 April 2013.",
    description: "Born 27 April 1967. First Dutch king since 1890 — three queens preceded him. Married Queen Máxima from Argentina.",
    startYear: 1967,
    coords: { lat: 52.3676, lng: 4.9041 },
    tags: ["monarch", "netherlands", "orange"],
    portraitUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Portret_van_Willem-Alexander%2C_2024_%28cropped%29.jpg/330px-Portret_van_Willem-Alexander%2C_2024_%28cropped%29.jpg",
  },
  {
    id: "king-philippe-belgium",
    kind: "person",
    name: "King Philippe of Belgium",
    calloutLabel: "Philippe",
    summary: "King of the Belgians since 21 July 2013.",
    description: "Born 15 April 1960. Constitutional monarch of a federal state with three language communities.",
    startYear: 1960,
    coords: { lat: 50.8503, lng: 4.3517 },
    tags: ["monarch", "belgium"],
  },
  {
    id: "king-felipe-vi",
    kind: "person",
    name: "King Felipe VI of Spain",
    calloutLabel: "Felipe VI",
    summary: "King of Spain since 19 June 2014.",
    description: "Born 30 January 1968. Assumed the throne following the abdication of his father, Juan Carlos I.",
    startYear: 1968,
    coords: { lat: 40.4168, lng: -3.7038 },
    tags: ["monarch", "spain", "bourbon"],
    portraitUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/ReyFelipeVI.jpg/330px-ReyFelipeVI.jpg",
  },
  {
    id: "grand-duke-henri",
    kind: "person",
    name: "Grand Duke Henri of Luxembourg",
    calloutLabel: "Henri",
    summary: "Grand Duke of Luxembourg since 7 October 2000.",
    description: "Born 16 April 1955. Married Grand Duchess María Teresa from Cuba.",
    startYear: 1955,
    coords: { lat: 49.6116, lng: 6.1319 },
    tags: ["monarch", "luxembourg", "nassau"],
  },
  {
    id: "prince-hans-adam-ii",
    kind: "person",
    name: "Prince Hans-Adam II of Liechtenstein",
    calloutLabel: "Hans-Adam II",
    summary: "Reigning Prince of Liechtenstein since 13 November 1989.",
    description: "Born 14 February 1945. One of the wealthiest monarchs in Europe. His son Prince Alois exercises most governmental duties.",
    startYear: 1945,
    coords: { lat: 47.1410, lng: 9.5209 },
    tags: ["monarch", "liechtenstein"],
  },
  {
    id: "prince-albert-ii-monaco",
    kind: "person",
    name: "Prince Albert II of Monaco",
    calloutLabel: "Albert II",
    summary: "Sovereign Prince of Monaco since 6 April 2005.",
    description: "Born 14 March 1958. Son of Prince Rainier III and American actress Grace Kelly. Married Charlene Wittstock in 2011.",
    startYear: 1958,
    coords: { lat: 43.7297, lng: 7.4142 },
    tags: ["monarch", "monaco", "grimaldi"],
    portraitUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Albrecht_II_Monaco_2015_%28cropped%29.jpg/330px-Albrecht_II_Monaco_2015_%28cropped%29.jpg",
  },
];

export const monarchyLinks: AtlasLink[] = [
  // Monarchs → capitals
  { id: "mk1", from: "king-charles-iii", to: "london", rel: "ruled", year: 2022 },
  { id: "mk2", from: "king-frederik-x", to: "copenhagen", rel: "ruled", year: 2024 },
  { id: "mk3", from: "king-harold-v-norway", to: "oslo", rel: "ruled", year: 1991 },
  { id: "mk4", from: "king-carl-xvi-gustaf", to: "stockholm", rel: "ruled", year: 1973 },
  { id: "mk5", from: "king-willem-alexander", to: "amsterdam", rel: "ruled", year: 2013 },
  { id: "mk6", from: "king-philippe-belgium", to: "brussels", rel: "ruled", year: 2013 },
  { id: "mk7", from: "king-felipe-vi", to: "madrid", rel: "ruled", year: 2014 },
  { id: "mk8", from: "grand-duke-henri", to: "luxembourg-city", rel: "ruled", year: 2000 },
  { id: "mk9", from: "prince-hans-adam-ii", to: "vaduz", rel: "ruled", year: 1989 },
  { id: "mk10", from: "prince-albert-ii-monaco", to: "monaco-city", rel: "ruled", year: 2005 },
  // Monarchs → houses
  { id: "mk11", from: "king-charles-iii", to: "house-windsor", rel: "member_of" },
  { id: "mk12", from: "king-frederik-x", to: "house-glucksburg", rel: "member_of" },
  { id: "mk13", from: "queen-mary-denmark", to: "house-glucksburg", rel: "member_of" },
  { id: "mk14", from: "king-harold-v-norway", to: "house-glucksburg", rel: "member_of" },
  { id: "mk15", from: "king-carl-xvi-gustaf", to: "house-bernadotte", rel: "member_of" },
  { id: "mk16", from: "king-willem-alexander", to: "house-orange-nassau", rel: "member_of" },
  { id: "mk17", from: "king-philippe-belgium", to: "house-belgium", rel: "member_of" },
  { id: "mk18", from: "king-felipe-vi", to: "house-bourbon-spain", rel: "member_of" },
  { id: "mk19", from: "grand-duke-henri", to: "house-nassau-weilburg", rel: "member_of" },
  { id: "mk20", from: "prince-hans-adam-ii", to: "house-liechtenstein", rel: "member_of" },
  { id: "mk21", from: "prince-albert-ii-monaco", to: "house-grimaldi", rel: "member_of" },
  // Descent links (all European monarchs descend from Queen Victoria through various lines)
  { id: "mk22", from: "king-charles-iii", to: "king-frederik-x", rel: "related", note: "Distant cousins through Queen Victoria." },
  { id: "mk23", from: "king-frederik-x", to: "king-harold-v-norway", rel: "related", note: "Both House of Glücksburg." },
  { id: "mk24", from: "king-frederik-x", to: "queen-mary-denmark", rel: "spouse_of", year: 2004 },
  // Windsor house descends from House of Saxe-Coburg
  { id: "mk25", from: "house-windsor", to: "house-belgium", rel: "descends_from", note: "Both trace to House of Saxe-Coburg and Gotha." },
];

export const monarchiesScene: AtlasScene = {
  id: "europe-monarchies-2025",
  title: "European Monarchies 2025",
  subtitle: "The 10 remaining European monarchies",
  year: 2025,
  center: { lat: 52, lng: 8 },
  zoom: 4,
  badge: "Europe 2025",
  calloutIds: [
    "king-charles-iii",
    "king-frederik-x",
    "king-harold-v-norway",
    "king-carl-xvi-gustaf",
    "king-willem-alexander",
    "king-philippe-belgium",
    "king-felipe-vi",
    "prince-albert-ii-monaco",
  ],
  focusId: "king-charles-iii",
};

export const monarchyEntities: AtlasEntity[] = [
  ...monarchyPlaces,
  ...monarchyHouses,
  ...monarchyPersons,
];
