import type { AtlasEntity, AtlasLink, AtlasScene } from "@/lib/atlas/types";

/**
 * Egyptian Gods — family tree of the major deities.
 * Coords = primary cult city on the Nile.
 */
export const egyptEntities: AtlasEntity[] = [
  // Primordial
  {
    id: "atum",
    kind: "deity",
    name: "Atum",
    calloutLabel: "Atum",
    summary: "The first god; self-created from the primordial waters of Nun.",
    description: "Ra-Atum was the setting sun and the creator in Heliopolitan theology. He created himself from the darkness and chaos, then created Shu and Tefnut by spitting or sneezing.",
    startYear: -3100,
    coords: { lat: 30.1286, lng: 31.3084 },
    tags: ["primordial", "creator", "sun", "heliopolis"],
  },
  {
    id: "ra",
    kind: "deity",
    name: "Ra",
    calloutLabel: "Ra",
    summary: "God of the sun and king of the gods; the midday sun.",
    description: "The supreme deity of the Egyptian pantheon, Ra traveled the sky in his solar barque by day and through the underworld (Duat) by night. Often merged with other gods as Ra-Atum, Amun-Ra, or Ra-Horakhty.",
    coords: { lat: 30.1286, lng: 31.3084 },
    tags: ["sun", "king", "heliopolis"],
  },
  {
    id: "nun",
    kind: "deity",
    name: "Nun",
    calloutLabel: "Nun",
    summary: "The primordial waters; chaos before creation.",
    description: "Nun personified the infinite, dark, watery chaos that existed before creation. The primordial source from which Atum emerged.",
    tags: ["primordial", "chaos", "water"],
  },
  // Ennead of Heliopolis
  {
    id: "shu",
    kind: "deity",
    name: "Shu",
    calloutLabel: "Shu",
    summary: "God of air and light; son of Atum.",
    description: "Shu held up the sky (Nut) and separated her from the earth (Geb). He personified sunlit air and supported cosmic order.",
    coords: { lat: 30.1286, lng: 31.3084 },
    tags: ["air", "light", "ennead"],
  },
  {
    id: "tefnut",
    kind: "deity",
    name: "Tefnut",
    calloutLabel: "Tefnut",
    summary: "Goddess of moisture; twin sister and wife of Shu.",
    description: "Together with Shu she represented the forces of dryness and moisture. Often depicted as a lioness or a woman with a lioness head.",
    coords: { lat: 30.1286, lng: 31.3084 },
    tags: ["moisture", "ennead", "lioness"],
  },
  {
    id: "geb",
    kind: "deity",
    name: "Geb",
    calloutLabel: "Geb",
    summary: "God of the earth; son of Shu and Tefnut.",
    description: "Geb lay beneath the sky (his sister Nut), from whom Shu separated them. Earthquakes were said to be his laughter. Father of Osiris, Isis, Seth, and Nephthys.",
    coords: { lat: 30.1286, lng: 31.3084 },
    tags: ["earth", "ennead"],
  },
  {
    id: "nut",
    kind: "deity",
    name: "Nut",
    calloutLabel: "Nut",
    summary: "Goddess of the sky; daughter of Shu and Tefnut.",
    description: "Nut arched over the earth as the sky, swallowing the sun at dusk and giving birth to it at dawn. Mother of Osiris, Isis, Seth, Nephthys, and in some texts Horus the Elder.",
    coords: { lat: 30.1286, lng: 31.3084 },
    tags: ["sky", "ennead", "mother"],
  },
  {
    id: "osiris",
    kind: "deity",
    name: "Osiris",
    calloutLabel: "Osiris",
    summary: "God of the dead and resurrection; judge of the afterlife.",
    description: "First king of Egypt in myth, murdered and dismembered by his brother Seth. Resurrected by Isis, he became lord of the underworld. The central figure of Egyptian funerary religion.",
    coords: { lat: 26.1615, lng: 32.7200 },
    tags: ["death", "resurrection", "king", "abydos"],
  },
  {
    id: "isis",
    kind: "deity",
    name: "Isis",
    calloutLabel: "Isis",
    summary: "Goddess of magic, healing, and motherhood; wife and resurrector of Osiris.",
    description: "Isis gathered the dismembered body of Osiris and resurrected him long enough to conceive Horus. Her cult spread across the Mediterranean world. One of the most beloved and enduring of all Egyptian deities.",
    coords: { lat: 24.0889, lng: 32.8998 },
    tags: ["magic", "healing", "mother", "philae"],
  },
  {
    id: "seth",
    kind: "deity",
    name: "Seth",
    calloutLabel: "Seth",
    summary: "God of chaos, storms, and the desert; murderer of Osiris.",
    description: "Seth killed Osiris out of jealousy, scattering his body across Egypt. He fought Horus for eighty years before the gods awarded Egypt to Horus. Seth also protected Ra on his nightly journey through the underworld.",
    coords: { lat: 25.6995, lng: 32.6421 },
    tags: ["chaos", "storm", "desert", "ombos"],
  },
  {
    id: "nephthys",
    kind: "deity",
    name: "Nephthys",
    calloutLabel: "Nephthys",
    summary: "Goddess of mourning and funerary rites; sister of Isis and Osiris.",
    description: "Despite being wife of Seth, Nephthys helped Isis reassemble Osiris. She was a goddess of death and mourning, protecting the dead.",
    coords: { lat: 30.1286, lng: 31.3084 },
    tags: ["mourning", "funerary", "ennead"],
  },
  // Horus family
  {
    id: "horus",
    kind: "deity",
    name: "Horus",
    calloutLabel: "Horus",
    summary: "God of the sky and kingship; son of Osiris and Isis.",
    description: "Horus avenged his father by defeating Seth. The living pharaoh was considered Horus incarnate. The Eye of Horus (Wedjat) is one of the most recognizable symbols of ancient Egypt.",
    coords: { lat: 26.0098, lng: 32.8998 },
    tags: ["sky", "kingship", "falcon", "edfu"],
  },
  {
    id: "anubis",
    kind: "deity",
    name: "Anubis",
    calloutLabel: "Anubis",
    summary: "God of embalming and guide of the dead; jackal-headed.",
    description: "Anubis presided over mummification and guided souls to the Hall of Two Truths. He weighed the heart against the feather of Ma'at. Son of Osiris and Nephthys in most traditions.",
    coords: { lat: 27.9158, lng: 30.7582 },
    tags: ["embalming", "jackal", "underworld", "cynopolis"],
  },
  // Other major deities
  {
    id: "thoth",
    kind: "deity",
    name: "Thoth",
    calloutLabel: "Thoth",
    summary: "God of wisdom, writing, and the moon; ibis-headed scribe of the gods.",
    description: "Thoth recorded the weighing of the heart in the Hall of Two Truths. Inventor of writing and the calendar. Mediator in the conflict between Horus and Seth.",
    coords: { lat: 27.7957, lng: 30.8965 },
    tags: ["wisdom", "writing", "moon", "ibis", "hermopolis"],
  },
  {
    id: "hathor",
    kind: "deity",
    name: "Hathor",
    calloutLabel: "Hathor",
    summary: "Goddess of love, beauty, music, and motherhood; cow goddess.",
    description: "Often depicted as a cow or a woman with cow horns. One of the most important and complex goddesses, associated with joy, feminine love, and the protection of women.",
    coords: { lat: 26.1207, lng: 32.8732 },
    tags: ["love", "beauty", "cow", "dendera"],
  },
  {
    id: "sekhmet",
    kind: "deity",
    name: "Sekhmet",
    calloutLabel: "Sekhmet",
    summary: "Lioness goddess of war and plague; destroyer who could also heal.",
    description: "Daughter of Ra. When Ra grew angry at humanity, he sent Sekhmet to destroy them. She was only stopped when tricked into drinking beer colored red like blood.",
    coords: { lat: 29.8784, lng: 31.2131 },
    tags: ["war", "plague", "lioness", "memphis"],
  },
  {
    id: "ptah",
    kind: "deity",
    name: "Ptah",
    calloutLabel: "Ptah",
    summary: "God of craftsmen and architects; creator by thought and word.",
    description: "Ptah created the world through his heart (thought) and tongue (speech). Chief deity of Memphis. Father of civilization and patron of all craftsmen.",
    coords: { lat: 29.8462, lng: 31.2511 },
    tags: ["crafts", "creation", "memphis"],
  },
  {
    id: "amun",
    kind: "deity",
    name: "Amun",
    calloutLabel: "Amun",
    summary: "King of the gods during the New Kingdom; merged with Ra as Amun-Ra.",
    description: "Originally a local deity of Thebes, Amun became the preeminent deity of all Egypt during the New Kingdom. His great temple at Karnak was the largest in Egypt.",
    coords: { lat: 25.7188, lng: 32.6571 },
    tags: ["king", "hidden", "thebes", "karnak"],
  },
  {
    id: "mut",
    kind: "deity",
    name: "Mut",
    calloutLabel: "Mut",
    summary: "Mother goddess and consort of Amun; queen of the gods.",
    description: "Mut means 'mother' in ancient Egyptian. As consort of Amun she formed part of the Theban Triad alongside their adopted son Khonsu.",
    coords: { lat: 25.7188, lng: 32.6571 },
    tags: ["mother", "thebes", "queen"],
  },
  {
    id: "khonsu",
    kind: "deity",
    name: "Khonsu",
    calloutLabel: "Khonsu",
    summary: "Moon god and healer; son of Amun and Mut.",
    description: "The third member of the Theban Triad. Khonsu was worshipped as a god of the moon and a healer. His great temple stood at Karnak.",
    coords: { lat: 25.7188, lng: 32.6571 },
    tags: ["moon", "healing", "thebes"],
  },
  {
    id: "bastet",
    kind: "deity",
    name: "Bastet",
    calloutLabel: "Bastet",
    summary: "Cat goddess of protection, fertility, and the home.",
    description: "Originally a fierce lioness warrior goddess, Bastet was later depicted as a domestic cat. She protected homes from evil spirits and disease, especially those affecting women and children.",
    coords: { lat: 30.5868, lng: 31.5082 },
    tags: ["cat", "protection", "fertility", "bubastis"],
  },
  {
    id: "sobek",
    kind: "deity",
    name: "Sobek",
    calloutLabel: "Sobek",
    summary: "Crocodile god of the Nile, strength, and military prowess.",
    description: "Sobek was associated with the fertility of the Nile and the power of the pharaoh. Live crocodiles were kept in his temples and adorned with gold jewelry.",
    coords: { lat: 29.3167, lng: 30.8667 },
    tags: ["crocodile", "nile", "power", "fayum"],
  },
  {
    id: "ma-at",
    kind: "deity",
    name: "Ma'at",
    calloutLabel: "Ma'at",
    summary: "Goddess of truth, justice, cosmic order, and morality.",
    description: "Ma'at personified the fundamental order of the universe. Her feather was weighed against the heart of the deceased to judge their worthiness for the afterlife. All pharaohs claimed to rule in her name.",
    tags: ["truth", "justice", "order", "cosmic"],
  },
  {
    id: "ra-horakhty",
    kind: "deity",
    name: "Ra-Horakhty",
    calloutLabel: "Ra-Horakhty",
    summary: "Syncretic falcon sun god; Ra merged with Horus of the Horizon.",
    description: "Ra-Horakhty represented the sun at the horizon — dawn and dusk. One of the most important cult forms at Heliopolis.",
    coords: { lat: 30.1286, lng: 31.3084 },
    tags: ["sun", "falcon", "syncretic", "heliopolis"],
  },
  // Places — cult centers
  {
    id: "heliopolis-egypt",
    kind: "place",
    name: "Heliopolis",
    summary: "City of the Sun; the oldest and greatest theological center of Egypt.",
    description: "Modern Ain Shams / Matariya in Cairo. Home of the Ennead and the Benben stone (original sacred obelisk).",
    coords: { lat: 30.1286, lng: 31.3084 },
    tags: ["cult-center", "sun", "ennead"],
  },
  {
    id: "thebes-egypt",
    kind: "place",
    name: "Thebes (Luxor)",
    summary: "New Kingdom capital; home of Amun's great Karnak temple complex.",
    description: "Modern Luxor. The largest ancient religious complex in the world. Amun, Mut, and Khonsu were worshipped here.",
    coords: { lat: 25.7188, lng: 32.6571 },
    tags: ["cult-center", "amun", "capital"],
  },
  {
    id: "memphis-egypt",
    kind: "place",
    name: "Memphis",
    summary: "Ancient capital near modern Cairo; cult city of Ptah and Sekhmet.",
    description: "One of the oldest and most important ancient Egyptian cities. Home of the Temple of Ptah.",
    coords: { lat: 29.8462, lng: 31.2511 },
    tags: ["cult-center", "ptah", "capital"],
  },
  {
    id: "abydos-egypt",
    kind: "place",
    name: "Abydos",
    summary: "Sacred city of Osiris; site of the oldest pharaonic tombs.",
    description: "Considered the burial place of Osiris. The annual Mysteries of Osiris were performed here.",
    coords: { lat: 26.1615, lng: 31.9198 },
    tags: ["cult-center", "osiris", "burial"],
  },
  {
    id: "edfu-egypt",
    kind: "place",
    name: "Edfu",
    summary: "Cult city of Horus; best-preserved temple complex in Egypt.",
    description: "The Temple of Horus at Edfu is the most complete of all Egyptian temples.",
    coords: { lat: 24.9782, lng: 32.8727 },
    tags: ["cult-center", "horus", "temple"],
  },
];

export const egyptLinks: AtlasLink[] = [
  // Ennead — creation
  { id: "eg1", from: "atum", to: "shu", rel: "parent_of" },
  { id: "eg2", from: "atum", to: "tefnut", rel: "parent_of" },
  { id: "eg3", from: "shu", to: "tefnut", rel: "spouse_of" },
  { id: "eg4", from: "shu", to: "geb", rel: "parent_of" },
  { id: "eg5", from: "shu", to: "nut", rel: "parent_of" },
  { id: "eg6", from: "tefnut", to: "geb", rel: "parent_of" },
  { id: "eg7", from: "tefnut", to: "nut", rel: "parent_of" },
  { id: "eg8", from: "geb", to: "nut", rel: "spouse_of" },
  // Ennead — second generation
  { id: "eg9", from: "geb", to: "osiris", rel: "parent_of" },
  { id: "eg10", from: "geb", to: "isis", rel: "parent_of" },
  { id: "eg11", from: "geb", to: "seth", rel: "parent_of" },
  { id: "eg12", from: "geb", to: "nephthys", rel: "parent_of" },
  { id: "eg13", from: "nut", to: "osiris", rel: "parent_of" },
  { id: "eg14", from: "nut", to: "isis", rel: "parent_of" },
  { id: "eg15", from: "nut", to: "seth", rel: "parent_of" },
  { id: "eg16", from: "nut", to: "nephthys", rel: "parent_of" },
  { id: "eg17", from: "osiris", to: "isis", rel: "spouse_of" },
  { id: "eg18", from: "seth", to: "nephthys", rel: "spouse_of" },
  { id: "eg19", from: "osiris", to: "seth", rel: "sibling_of" },
  { id: "eg20", from: "osiris", to: "isis", rel: "sibling_of" },
  // Third generation
  { id: "eg21", from: "osiris", to: "horus", rel: "parent_of" },
  { id: "eg22", from: "isis", to: "horus", rel: "parent_of" },
  { id: "eg23", from: "osiris", to: "anubis", rel: "parent_of" },
  { id: "eg24", from: "nephthys", to: "anubis", rel: "parent_of" },
  // Ra lineage
  { id: "eg25", from: "ra", to: "atum", rel: "related", note: "Often merged as Ra-Atum." },
  { id: "eg26", from: "ra", to: "sekhmet", rel: "parent_of" },
  { id: "eg27", from: "ra", to: "hathor", rel: "parent_of", note: "In some traditions." },
  { id: "eg28", from: "ra", to: "ma-at", rel: "parent_of", note: "Ma'at as daughter of Ra in many texts." },
  // Theban triad
  { id: "eg29", from: "amun", to: "mut", rel: "spouse_of" },
  { id: "eg30", from: "amun", to: "khonsu", rel: "parent_of" },
  { id: "eg31", from: "mut", to: "khonsu", rel: "parent_of" },
  // Cult cities
  { id: "eg32", from: "ra", to: "heliopolis-egypt", rel: "related" },
  { id: "eg33", from: "atum", to: "heliopolis-egypt", rel: "related" },
  { id: "eg34", from: "amun", to: "thebes-egypt", rel: "related" },
  { id: "eg35", from: "mut", to: "thebes-egypt", rel: "related" },
  { id: "eg36", from: "khonsu", to: "thebes-egypt", rel: "related" },
  { id: "eg37", from: "ptah", to: "memphis-egypt", rel: "related" },
  { id: "eg38", from: "sekhmet", to: "memphis-egypt", rel: "related" },
  { id: "eg39", from: "osiris", to: "abydos-egypt", rel: "related" },
  { id: "eg40", from: "horus", to: "edfu-egypt", rel: "related" },
  { id: "eg41", from: "thoth", to: "ma-at", rel: "related", note: "Thoth recorded Ma'at's judgments." },
];

export const egyptScene: AtlasScene = {
  id: "egypt-gods",
  title: "Egyptian Pantheon",
  subtitle: "Family tree of the major Egyptian deities",
  year: -3000,
  center: { lat: 27.2, lng: 31.5 },
  zoom: 5,
  badge: "Egyptian Pantheon",
  calloutIds: [
    "ra",
    "osiris",
    "isis",
    "horus",
    "seth",
    "anubis",
    "hathor",
    "thoth",
    "amun",
    "heliopolis-egypt",
    "thebes-egypt",
    "memphis-egypt",
    "abydos-egypt",
  ],
  focusId: "ra",
};
