import type { AtlasEntity, AtlasLink, AtlasScene } from "@/lib/atlas/types";

/**
 * Language Families and Writing Systems — geographic spread and descent tree.
 */
export const languageEntities: AtlasEntity[] = [
  // Language families — geographic centers
  {
    id: "lang-indo-european",
    kind: "concept",
    name: "Indo-European",
    summary: "The largest language family by speakers; spans from India to Iceland.",
    description: "Includes Germanic, Romance, Slavic, Celtic, Indo-Iranian, Greek, Albanian, and Armenian branches. Descended from a common Proto-Indo-European ancestor spoken ~4500 BCE on the Pontic steppe.",
    startYear: -4500,
    coords: { lat: 47.5, lng: 35.0 },
    tags: ["language-family", "proto-indo-european", "steppe"],
  },
  {
    id: "lang-germanic",
    kind: "concept",
    name: "Germanic Languages",
    summary: "Branch of Indo-European including English, German, Dutch, Nordic languages.",
    description: "English is the most widely spoken Germanic language. Descended from Proto-Germanic (~500 BCE). North Germanic → Scandinavian; West Germanic → English, German, Dutch; East Germanic → Gothic (extinct).",
    startYear: -500,
    coords: { lat: 54.0, lng: 12.0 },
    tags: ["language-branch", "germanic", "english", "german"],
  },
  {
    id: "lang-romance",
    kind: "concept",
    name: "Romance Languages",
    summary: "Branch of Indo-European descended from Vulgar Latin; includes Spanish, French, Italian, Portuguese, Romanian.",
    description: "Spread by the Roman Empire. Spanish and Portuguese expanded globally through colonialism — today ~500 million Spanish speakers and ~230 million Portuguese speakers.",
    startYear: -200,
    coords: { lat: 43.0, lng: 5.0 },
    tags: ["language-branch", "romance", "latin", "spanish", "french"],
  },
  {
    id: "lang-slavic",
    kind: "concept",
    name: "Slavic Languages",
    summary: "Branch of Indo-European spanning Eastern Europe and northern Asia; Russian is the largest.",
    description: "Divided into East Slavic (Russian, Ukrainian, Belarusian), West Slavic (Polish, Czech, Slovak), and South Slavic (Serbian, Croatian, Bulgarian, Slovenian).",
    startYear: 0,
    coords: { lat: 55.0, lng: 37.0 },
    tags: ["language-branch", "slavic", "russian", "polish"],
  },
  {
    id: "lang-indo-iranian",
    kind: "concept",
    name: "Indo-Iranian Languages",
    summary: "Branch of Indo-European including Sanskrit and its descendants; Hindi, Urdu, Persian, Bengali.",
    description: "The Indo-Iranian branch is the largest sub-family by number of speakers. Includes the Indo-Aryan languages (Hindi, Bengali, Punjabi) and the Iranian languages (Persian/Farsi, Pashto, Kurdish).",
    startYear: -2000,
    coords: { lat: 30.0, lng: 68.0 },
    tags: ["language-branch", "sanskrit", "hindi", "persian"],
  },
  {
    id: "lang-afro-asiatic",
    kind: "concept",
    name: "Afro-Asiatic",
    summary: "Language family spanning North Africa and the Middle East; includes Arabic, Hebrew, Amharic.",
    description: "Second-largest family by number of speakers (~400 million). Semitic branch includes Arabic (largest Semitic language), Hebrew, and Amharic. Berber, Cushitic, and Egyptian (ancient) branches complete the family.",
    startYear: -8000,
    coords: { lat: 15.0, lng: 30.0 },
    tags: ["language-family", "arabic", "hebrew", "semitic"],
  },
  {
    id: "lang-sino-tibetan",
    kind: "concept",
    name: "Sino-Tibetan",
    summary: "Language family including Mandarin Chinese, Tibetan, and Burmese.",
    description: "Second-largest family by native speakers. Mandarin alone has ~920 million native speakers. Includes the Sinitic (Chinese) and Tibeto-Burman branches.",
    startYear: -5000,
    coords: { lat: 35.0, lng: 105.0 },
    tags: ["language-family", "chinese", "mandarin", "tibetan"],
  },
  {
    id: "lang-niger-congo",
    kind: "concept",
    name: "Niger-Congo",
    summary: "Largest language family by number of distinct languages; Bantu sub-family dominates sub-Saharan Africa.",
    description: "Over 1,500 languages. The Bantu expansion ~3000 BCE spread languages across sub-Saharan Africa. Swahili, Zulu, Yoruba, Igbo, and Shona are major members.",
    startYear: -3000,
    coords: { lat: 5.0, lng: 18.0 },
    tags: ["language-family", "bantu", "swahili", "yoruba", "africa"],
  },
  {
    id: "lang-austronesian",
    kind: "concept",
    name: "Austronesian",
    summary: "Language family spanning the Pacific and Indian Oceans; Hawaiian, Malay, Tagalog, Malagasy.",
    description: "Remarkable for its geographic spread across the Pacific — one of the widest distributions of any language family. Originated in Taiwan ~3000 BCE.",
    startYear: -3000,
    coords: { lat: 5.0, lng: 120.0 },
    tags: ["language-family", "malay", "tagalog", "pacific"],
  },
  {
    id: "lang-turkic",
    kind: "concept",
    name: "Turkic Languages",
    summary: "Language family stretching from Turkey to Siberia; Turkish, Uzbek, Kazakh, Azerbaijani.",
    description: "Descended from Proto-Turkic spoken on the Eurasian steppe. Spread by nomadic peoples across Central Asia and Anatolia. Turkish is the largest member.",
    startYear: -1000,
    coords: { lat: 42.0, lng: 55.0 },
    tags: ["language-family", "turkish", "central-asia", "steppe"],
  },
  {
    id: "lang-dravidian",
    kind: "concept",
    name: "Dravidian Languages",
    summary: "Language family of South India and Sri Lanka; Tamil is the oldest living member.",
    description: "Predates the Indo-Aryan migration into India. Tamil has a literary tradition going back over 2,000 years. Major members: Tamil, Telugu, Kannada, Malayalam.",
    startYear: -4000,
    coords: { lat: 12.0, lng: 79.0 },
    tags: ["language-family", "tamil", "south-india", "dravidian"],
  },
  {
    id: "lang-japonic",
    kind: "concept",
    name: "Japonic Languages",
    summary: "Language family of Japan; Japanese and Ryukyuan.",
    description: "Japanese is a language isolate within a small family. Written using three scripts: hiragana, katakana (both syllabaries), and kanji (Chinese characters).",
    startYear: -1000,
    coords: { lat: 36.0, lng: 138.0 },
    tags: ["language-family", "japanese", "japan"],
  },
  {
    id: "lang-koreanic",
    kind: "concept",
    name: "Koreanic Languages",
    summary: "Korean — spoken by ~80 million people; its genetic relationships are debated.",
    description: "Korean is sometimes grouped with the Altaic hypothesis alongside Turkic and Mongolic, but most linguists treat it as an isolate.",
    startYear: -500,
    coords: { lat: 37.5, lng: 127.5 },
    tags: ["language-family", "korean", "korea"],
  },
  {
    id: "lang-uralic",
    kind: "concept",
    name: "Uralic Languages",
    summary: "Language family including Finnish, Estonian, and Hungarian.",
    description: "Notable for being non-Indo-European families surrounded by Indo-European languages in Europe. Proto-Uralic was spoken near the Ural Mountains ~4000 BCE.",
    startYear: -4000,
    coords: { lat: 62.0, lng: 55.0 },
    tags: ["language-family", "finnish", "hungarian", "uralic"],
  },
  {
    id: "lang-celtic",
    kind: "concept",
    name: "Celtic Languages",
    summary: "Branch of Indo-European; Welsh, Irish Gaelic, Scottish Gaelic, Breton.",
    description: "Once spoken across much of Europe, now confined to Atlantic fringe areas. Irish is the oldest written vernacular in Western Europe.",
    startYear: -800,
    coords: { lat: 53.0, lng: -5.0 },
    tags: ["language-branch", "welsh", "irish", "celtic"],
  },
  // Writing systems
  {
    id: "script-phoenician",
    kind: "concept",
    name: "Phoenician Alphabet",
    summary: "~1050 BCE; the ancestor of most modern alphabets.",
    description: "The Phoenician script had 22 consonants (no vowels) and was written right to left. It spread across the Mediterranean through Phoenician trade networks, giving rise to Greek, Aramaic, Hebrew, and Latin scripts.",
    startYear: -1050,
    coords: { lat: 33.8886, lng: 35.4955 },
    tags: ["writing-system", "alphabet", "ancestor", "phoenicia"],
  },
  {
    id: "script-greek",
    kind: "concept",
    name: "Greek Alphabet",
    summary: "~800 BCE; first alphabet with vowels; ancestor of Latin and Cyrillic.",
    description: "Adapted from Phoenician but added vowel letters — a transformative innovation. Gave rise to the Latin alphabet (via Etruscan) and the Cyrillic alphabet.",
    startYear: -800,
    coords: { lat: 37.9838, lng: 23.7275 },
    tags: ["writing-system", "alphabet", "vowels", "greek"],
  },
  {
    id: "script-latin",
    kind: "concept",
    name: "Latin Alphabet",
    summary: "~600 BCE; now the most widely used writing system in the world.",
    description: "Derived from the Greek alphabet via Etruscan. Used by the Roman Empire and spread globally by European colonialism. ~70% of the world's languages use Latin script today.",
    startYear: -600,
    coords: { lat: 41.9028, lng: 12.4964 },
    tags: ["writing-system", "alphabet", "latin", "rome"],
  },
  {
    id: "script-arabic",
    kind: "concept",
    name: "Arabic Script",
    summary: "~400 CE; second most widely used script; written right to left.",
    description: "Descended from Aramaic (which descended from Phoenician). Used for Arabic, Persian, Urdu, and other languages. About 700 million people use Arabic script.",
    startYear: 400,
    coords: { lat: 21.3891, lng: 39.8579 },
    tags: ["writing-system", "abjad", "rtl", "arabic"],
  },
  {
    id: "script-cyrillic",
    kind: "concept",
    name: "Cyrillic Script",
    summary: "~940 CE; created by Saints Cyril and Methodius for Slavic languages.",
    description: "Based on Greek uncial script. Now used for Russian, Ukrainian, Bulgarian, Serbian, and dozens of languages across former Soviet republics.",
    startYear: 940,
    coords: { lat: 42.6977, lng: 23.3219 },
    tags: ["writing-system", "alphabet", "slavic", "cyrillic"],
  },
  {
    id: "script-cuneiform",
    kind: "concept",
    name: "Cuneiform",
    summary: "~3400 BCE; one of the earliest writing systems; Mesopotamia.",
    description: "Invented by the Sumerians for accounting and administration, later used for literature (the Epic of Gilgamesh). Wedge-shaped marks pressed into clay tablets. Used for ~3,000 years.",
    startYear: -3400,
    coords: { lat: 31.9686, lng: 44.5041 },
    tags: ["writing-system", "ancient", "sumerian", "mesopotamia"],
  },
  {
    id: "script-hieroglyphics",
    kind: "concept",
    name: "Egyptian Hieroglyphics",
    summary: "~3200 BCE; sacred pictorial script of ancient Egypt.",
    description: "One of the earliest writing systems, used for religious and monumental texts. Deciphered in the 19th century using the Rosetta Stone.",
    startYear: -3200,
    coords: { lat: 25.6872, lng: 32.6396 },
    tags: ["writing-system", "ancient", "egypt", "sacred"],
  },
  {
    id: "script-chinese",
    kind: "concept",
    name: "Chinese Characters (Hanzi)",
    summary: "~1250 BCE (oracle bones); still in use today.",
    description: "One of the world's oldest writing systems still in continuous use. About 50,000 characters exist; ~3,000–4,000 needed for literacy. Used for Chinese, Japanese (kanji), and historically Korean (hanja).",
    startYear: -1250,
    coords: { lat: 34.3416, lng: 108.9398 },
    tags: ["writing-system", "logographic", "chinese", "hanzi"],
  },
];

export const languageLinks: AtlasLink[] = [
  // Indo-European branches
  { id: "ll1", from: "lang-indo-european", to: "lang-germanic", rel: "parent_of" },
  { id: "ll2", from: "lang-indo-european", to: "lang-romance", rel: "parent_of" },
  { id: "ll3", from: "lang-indo-european", to: "lang-slavic", rel: "parent_of" },
  { id: "ll4", from: "lang-indo-european", to: "lang-indo-iranian", rel: "parent_of" },
  { id: "ll5", from: "lang-indo-european", to: "lang-celtic", rel: "parent_of" },
  // Script descent chain
  { id: "ll6", from: "script-phoenician", to: "script-greek", rel: "descends_from" },
  { id: "ll7", from: "script-greek", to: "script-latin", rel: "parent_of" },
  { id: "ll8", from: "script-greek", to: "script-cyrillic", rel: "parent_of" },
  { id: "ll9", from: "script-phoenician", to: "script-arabic", rel: "descends_from", note: "Via Aramaic." },
  // Ancient scripts
  { id: "ll10", from: "script-cuneiform", to: "script-phoenician", rel: "influenced_by", note: "Early writing concepts." },
  // Languages → scripts
  { id: "ll11", from: "lang-romance", to: "script-latin", rel: "writes_in" },
  { id: "ll12", from: "lang-germanic", to: "script-latin", rel: "writes_in" },
  { id: "ll13", from: "lang-slavic", to: "script-cyrillic", rel: "writes_in" },
  { id: "ll14", from: "lang-afro-asiatic", to: "script-arabic", rel: "writes_in" },
  { id: "ll15", from: "lang-sino-tibetan", to: "script-chinese", rel: "writes_in" },
  { id: "ll16", from: "script-hieroglyphics", to: "script-phoenician", rel: "related", note: "Historical debate on influence." },
  // Spread
  { id: "ll17", from: "lang-indo-european", to: "lang-uralic", rel: "related", note: "Shared geography; borrowed extensively." },
  { id: "ll18", from: "lang-slavic", to: "script-cyrillic", rel: "related" },
];

export const languagesScene: AtlasScene = {
  id: "language-families",
  title: "Language Families",
  subtitle: "The major language families of the world",
  year: 2025,
  center: { lat: 30.0, lng: 25.0 },
  zoom: 2,
  badge: "Language Families",
  calloutIds: [
    "lang-indo-european",
    "lang-afro-asiatic",
    "lang-sino-tibetan",
    "lang-niger-congo",
    "lang-austronesian",
    "script-phoenician",
    "script-latin",
    "script-arabic",
    "script-chinese",
    "script-cuneiform",
  ],
  focusId: "lang-indo-european",
};
